apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatapp-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat-bot
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/chatapp-281611/chat_bot:v1
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

